# fly.toml app configuration file generated for threads-scraper on 2025-07-21T23:56:34-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'threads-scraper'
primary_region = 'sea'

[env]

[processes]
  worker = "python -m src.main"

[[jobs]]
  name = "scrape-every-5-min"
  schedule = "*/5 * * * *"
  command = "python -m src.main"

[[vm]]
  memory = '2048mb'
  cpu_kind = 'performance'
  cpus = 1
