# fly.toml app configuration file generated for threads-scraper on 2025-07-21T23:56:34-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'threads-scraper'
primary_region = 'sea'

[env]
  # Browser optimization flags
  PLAYWRIGHT_BROWSERS_PATH = '/app/.cache/playwright'
  PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD = '0'

# Configure machine to auto-suspend when not in use
[experimental]
  # Allow machine to be suspended when not in use
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  memory = '2048mb'
  cpu_kind = 'shared'
  cpus = 2

# Volume for browser profiles and cache
[[mounts]]
  source = "browser_cache"
  destination = "/app/.cache"
