# fly.toml app configuration file generated for threads-scraper on 2025-07-21T23:56:34-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'threads-scraper'
primary_region = 'sea'

[env]
  # Browser optimization flags
  # Let Playwright manage its own browser cache location per user
  PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD = '0'
  # Writable location for method history file used by src/method_tracker.py
  METHOD_HISTORY_DIR = '/app/.cache/method_history'

# No default process; machine idles until we exec the scraper command

[[vm]]
  memory = '2048mb'
  cpu_kind = 'shared'
  cpus = 2
  auto_stop = true
  auto_start = true

# Volume for browser profiles and cache
[[mounts]]
  source = "browser_cache"
  destination = "/app/.cache"

# Keep process group aligned with existing machine to avoid creating new group during deploy
[processes]
  app = "sleep infinity"
