name: Scheduled Scrape

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Run scraper on Fly.io
        run: ./scripts/run_machine.sh
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          # Updated machine ID after optimization deployment
          SCRAPER_MACHINE_ID: ${{ secrets.SCRAPER_MACHINE_ID }}
