name: Scheduled Scrape

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    steps:
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Run Scraper on Fly.io
        run: flyctl machines run --rm -a threads-scraper registry.fly.io/threads-scraper:latest -- python -m src.main
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }} 